# Generated by Django 4.2 on 2023-09-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbleitor",
            name="cep",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name="tbleitor",
            name="cidade",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name="tbleitor",
            name="estado",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name="tbleitor",
            name="numero",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
