# Generated by Django 4.2 on 2023-04-19 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbemprestimo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tbleitor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tblivro',
            options={},
        ),
    ]
