# Generated by Django 4.2 on 2023-09-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0002_tbleitor_cep_tbleitor_cidade_tbleitor_estado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbleitor",
            name="visivel",
            field=models.BooleanField(default=True),
        ),
    ]
