# Generated by Django 4.2 on 2023-10-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0003_tbleitor_visivel"),
    ]

    operations = [
        migrations.AddField(
            model_name="tblivro",
            name="visivel",
            field=models.BooleanField(default=True),
        ),
    ]
