# Generated by Django 4.2 on 2024-04-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_tblivro_visivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblivro',
            name='na',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tblivro',
            name='tombo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
