# Generated by Django 4.2 on 2024-04-02 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_alter_tblivro_na_alter_tblivro_tombo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblivro',
            name='tombo',
        ),
    ]
